export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Standy Group LLC",
  headline: "blablalalaallalalaal",
  description: "blablalalaallalalaal",
  buttonLable: "Get started",
  imgStart: false,
  img: require("../../images/svg-1.svg"),
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "welf;klwehf;lwehf",
  headline: "blablalalaallalalaal",
  description: "blablalalaallalalaal",
  buttonLable: "Learn more",
  imgStart: true,
  img: require("../../images/svg-2.svg"),
  alt: "Piggy",
  dark: false,
  primary: false,
  darkText: true,
};

export const homeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Standy Group LLC",
  headline: "blablalalaallalalaal",
  description: "blablalalaallalalaal",
  buttonLable: "Start Now",
  imgStart: false,
  img: require("../../images/svg-3.svg"),
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};
